# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lightening' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lightening

  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'lottie-ios'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift', '8.3.0-beta'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod ‘Firebase/Auth’
  pod 'JGProgressHUD'
  pod 'Firebase/Crashlytics'
  target 'LighteningTests' do
        inherit! :search_paths
        pod 'Firebase'
   end
end
